name: app

type: php:5.6

runtime:
    extensions:
        - intl

dependencies:
    php:
        composer/composer: "2.2.24"
build:
    flavor: none

hooks:
    build: |
        composer --no-ansi --no-interaction install --no-progress

web:
    commands:
        start: sleep
    locations:
        "/":
            root: "public"
            index:
                - "index.html"
            scripts: false
            expires: 10m

disk: 256
