name: app

type: php:5.6

build:
    flavor: composer

web:
    commands:
        start: sleep
    locations:
        "/":
            root: "public"
            index:
                - "index.html"
            scripts: false
            expires: 10m

disk: 256
